"""add upload file hash

Revision ID: 402ccd884bb2
Revises: 99cd652c1c3e
Create Date: 2026-02-02 07:37:44.906494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402ccd884bb2'
down_revision: Union[str, None] = '99cd652c1c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('raw_file_sha256', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'raw_file_sha256')
    # ### end Alembic commands ###
